### ISSUE TITLE
How to create a middleware only if condition valid ?

### ISSUE THREAD

**Issue by ghost** [middlewares/psr15-middlewares#3]
Hi,

I try to create a Middleware only if a condition is valid. For example I want to attach the middleware Shutdown only if the maintenance mode is active on my site. How can I do that ?

Regards

**Comment by oscarotero** [comment]
That deppends of the middleware dispatcher you're using, not the middleware itself. There's some dispatchers that allows to add middlewares under certain condition, but this is out of the scope of this project.
Other way is creating the array of middleware before the dispatcher. Example:

```php
$middleware = [
    new Middleware1(),
    new Middleware2(),
];
if ($condition === true) {
    $middleware[] = new Middleware3();
}

$dispatcher = new Dispatcher($middleware);
```

**Comment by ghost** [comment]
Hi,

thanks for your answer....don't ask me why I didn't think to do it this way.....(why to do simple ??).

Regards
