### ISSUE TITLE
Middleware CSRF PSR-15

### ISSUE THREAD

**Issue by terabytesoftw** [middlewares/psr15-middlewares#7]
Hi good morning, first of all thanks for the middleware, I wanted to know if the psr7 csrf middleware was updated to psr15,

Thank you.

**Comment by oscarotero** [comment]
Hi!
Sorry but csrf middleware wasn't ported yet to PSR-15. I didn't find a good way to implement this functionality. You have more info here: https://github.com/middlewares/ideas/issues/3
